name: pawpal_pet_adoption
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.4.18
  google_geocoding_api: ^1.5.2
                                                                      
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/